### ISSUE TITLE
Use table components in haddock3 libplots.py

### ISSUE THREAD

**Issue by sverhoeven** [i-VRESSE/haddock3-ui#6]
Use html like https://github.com/i-VRESSE/haddock3-ui/blob/main/example.html in libplots.py of haddock3.

Was blocked by #5

**Comment by sverhoeven** [comment]
Now example.html gives

``
`colormaker.ts:126 Uncaught (in promise) TypeError: P1.scale is not a function
    at ra.getScale (colormaker.ts:126:8)
    at chainname-colormaker.ts:40:45
    at Gt.eachModel (structure.ts:660:9)
    at new ra (chainname-colormaker.ts:29:22)
    at Object.getScheme (colormaker-registry.ts:103:12)
    at ar.getSubdividedColor (spline.ts:517:41)
    at cartoon-representation.ts:145:29
    at n.eachPolymer (chain-proxy.ts:277:9)
    at model-proxy.ts:139:14
    at n.eachChain (model-proxy.ts:179:9)
Show 37 more frames

```

**Comment by sverhoeven** [comment]
The table from haddock3-ui looks different than the one from analysis-components.
![_home_verhoes_git_vre4imbc_haddock3-ui_example html](https://github.com/user-attachments/assets/7d771f52-71ca-424f-8396-4fccb206b0d1)
![_home_verhoes_git_vre4imbc_haddock3-ui_example html (1)](https://github.com/user-attachments/assets/fff47c89-8cd8-420d-bc4a-a4eefeb82d7a)

but all functionality is retained.

**Comment by sverhoeven** [comment]
Also see https://github.com/i-VRESSE/haddock3-analysis-components/issues/17
